@username = admin
@password = admin
@host = http://localhost:4004
@auth = {{username}}:{{password}}


### Test GET Claim Service Value By Type with Basic Auth
GET http://localhost:4004/app/claim/analytics/ClaimsValueByTypeYear HTTP/1.1
Authorization: Basic {{auth}}

###

### Test GET Claim Service Value By Type with Basic Auth
GET http://localhost:4004/app/claim/analytics/RepsByOpenValue HTTP/1.1
Authorization: Basic {{auth}}

###