@username = admin
@password = admin
@host = http://localhost:4004
@auth = {{username}}:{{password}}


### Test GET Claim Service Metadata with Basic Auth
GET http://localhost:4004/app/claim/$metadata HTTP/1.1
Authorization: Basic {{auth}}

###

### Test GET for Claims with Basic Auth
GET http://localhost:4004/app/claim/Claims(ID=3b241101-e2bb-4255-8caf-4136c566a983,IsActiveEntity=true) HTTP/1.1
Authorization: Basic {{auth}}

###

### Test GET for Claims with Basic Auth
GET http://localhost:4004/app/claim/Claims HTTP/1.1
Authorization: Basic {{auth}}

###

### Test GET for Claims + Status + Type with Basic Auth
GET http://localhost:4004/app/claim/Claims?$expand=status,type HTTP/1.1
Authorization: Basic {{auth}}

###

### Test GET for Claims + Comments + Costs with Basic Auth
GET http://localhost:4004/app/claim/Claims?$expand=comments,costs HTTP/1.1
Authorization: Basic {{auth}}

###

### Test GET for Claims + Packaging Claim with Basic Auth
GET http://localhost:4004/app/claim/Claims?$expand=packagingClaim HTTP/1.1
Authorization: Basic {{auth}}

###

### Test GET for Claims + Quality Claim with Basic Auth
GET http://localhost:4004/app/claim/Claims?$expand=qualityClaim&$filter=type_id eq 'QC' HTTP/1.1
Authorization: Basic {{auth}}

###

### Test GET for Costs with Basic Auth
GET http://localhost:4004/app/claim/Costs HTTP/1.1
Authorization: Basic {{auth}}

###


### Test GET for Comments with Basic Auth
GET http://localhost:4004/app/claim/Comments HTTP/1.1
Authorization: Basic {{auth}}

###

### Test GET for QualityClaims with Basic Auth
GET http://localhost:4004/app/claim/QualityClaims HTTP/1.1
Authorization: Basic {{auth}}

###

### Test GET for PackagingClaims with Basic Auth
GET http://localhost:4004/app/claim/PackagingClaims HTTP/1.1
Authorization: Basic {{auth}}

###

### Test GET for Deliveries with Basic Auth
GET http://localhost:4004/app/claim/Deliveries HTTP/1.1
Authorization: Basic {{auth}}

###

### Test GET for Draft Attachments with Basic Auth
GET http://localhost:4004/app/claim/Attachments?$filter=IsActiveEntity eq false HTTP/1.1
Authorization: Basic {{auth}}

###


### Test GET for Attachments with Basic Auth
GET http://localhost:4004/app/claim/Attachments HTTP/1.1
Authorization: Basic {{auth}}

###


### Test GET Attachment Content with Basic Auth
GET http://localhost:4004/app/claim/Attachments(4b241101-e2bb-4255-8caf-4136c566a979,IsActiveEntity=true)/content HTTP/1.1
Authorization: Basic {{auth}}

###

### Test GET attachments via navigation from claim with Basic Auth
GET http://localhost:4004/app/claim/Claims(ID=3b241101-e2bb-4255-8caf-4136c566a979,IsActiveEntity=true)/attachments HTTP/1.1
Authorization: Basic {{auth}}

###

### Test GET attachment via navigation from claim with Basic Auth
GET http://localhost:4004/app/claim/Claims(ID=3b241101-e2bb-4255-8caf-4136c566a979,IsActiveEntity=true)/attachments(4b241101-e2bb-4255-8caf-4136c566a979) HTTP/1.1
Authorization: Basic {{auth}}

###

### Test POST attachment create via navigation from claim with Basic Auth
POST http://localhost:4004/app/claim/Attachments HTTP/1.1
Authorization: Basic {{auth}}
content-type: application/json

{
    "id":"5b241101-e2bb-4255-8caf-4136c566a979",
    "name": "logo.png",
    "contentType": "image/png",
    "createdBy": "patelka@tandg.global",
    "creationDate": "2024-04-01",
    "claim_ID": "3b241101-e2bb-4255-8caf-4136c566a979"
}

### Test PUT attachment create via navigation from claim with Basic Auth
PUT http://localhost:4004/app/claim/Attachments(5b241101-e2bb-4255-8caf-4136c566a979)/content HTTP/1.1
Authorization: Basic {{auth}}
Content-Type: image/png

< ./images/logo.png
###


### Test GET Attachment Content with Basic Auth
GET http://localhost:4004/app/claim/Attachments(5b241101-e2bb-4255-8caf-4136c566a979)/content HTTP/1.1
Authorization: Basic {{auth}}

###


### Test POST for Submit for Review with Basic Auth
POST http://localhost:4004/app/claim/Claims(ID=3b241101-e2bb-4255-8caf-4136c566a979,IsActiveEntity=true)/ClaimAppService.submitForReview HTTP/1.1
Authorization: Basic {{auth}}
content-type: application/json

###


### Test GET Growers Report with Basic Auth 
GET http://localhost:4004/app/getGrowersReport?claimId=3b241101-e2bb-4255-8caf-4136c566a979 HTTP/1.1
Authorization: Basic {{auth}}
content-type: application/json

###


### Test GET for Claims Quality Values
GET {{host}}/app/claim/Claims(ID=3b241101-e2bb-4255-8caf-4136c566a979,IsActiveEntity=true)/qualityClaim?$select=IsActiveEntity,claim_ID,claim_value_per_tce,percentage_claimed HTTP/1.1
Authorization: Basic {{auth}}
content-type: application/json

###

### Test GET for Claims Quality Values
GET {{host}}/app/claim/Claims(ID=3b241101-e2bb-4255-8caf-4136c566a979,IsActiveEntity=true) HTTP/1.1
Authorization: Basic {{auth}}
content-type: application/json

###


