
@host = http://localhost:5678/

@N8N_API_KEY = {{$dotenv N8N_API_KEY}}

### Trigger Webhook with API Key (Had to set the webhook to use header auth and use  header X-N8N-API-KEY in order to use cap-n8n plugin)
POST {{host}}webhook/submitClaimReview HTTP/1.1
X-N8N-API-KEY: {{N8N_API_KEY}}
Content-Type: application/json


### Get Workflow Details via REST API
GET {{host}}api/v1/workflows/ilkNoziH22zXfqr0 HTTP/1.1
X-N8N-API-KEY: {{N8N_API_KEY}}
Content-Type: application/json
